name: Deploy
on:
  workflow_dispatch: # Temporary dismantle of the AWS push path since this project focuses on 
#  push:             # Azure. Leaving wiring in place for future development on agnostic CI/CD pipeline
#    branches: [main]
#    paths:
#      - '**.go'
#      - 'template.yaml'
#      - 'samconfig.toml'
#      - 'go.mod'
#      - 'go.sum'
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::834424013123:role/JobFinderDeploy #needs to be changed for alternate users, want to pull into Github vars when I remember
          role-session-name: jobfinder-deploy
          aws-region: us-east-2 #might need to be changed for alternate users, want to pull into Github vars when I remember
      - run: sam build
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset